// Mocks generated by Mockito 5.2.0 from annotations
// in kweeksnews_app/test/features/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:kweeksnews_app/core/datasources/wp_remote_data_source.dart'
    as _i7;
import 'package:kweeksnews_app/core/models/category_model.dart' as _i3;
import 'package:kweeksnews_app/core/models/post_list_model.dart' as _i5;
import 'package:kweeksnews_app/core/models/post_model.dart' as _i6;
import 'package:kweeksnews_app/core/models/tag_model.dart' as _i4;
import 'package:kweeksnews_app/core/models/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

class _FakeCategoryModel_1 extends _i1.Fake implements _i3.CategoryModel {}

class _FakeTagModel_2 extends _i1.Fake implements _i4.TagModel {}

class _FakePostListModel_3 extends _i1.Fake implements _i5.PostListModel {}

class _FakePostModel_4 extends _i1.Fake implements _i6.PostModel {}

/// A class which mocks [WpRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWpRemoteDataSource extends _i1.Mock
    implements _i7.WpRemoteDataSource {
  MockWpRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.UserModel> getUser(
          {String? id, String? idType, bool? forceRefresh}) =>
      (super.noSuchMethod(
              Invocation.method(#getUser, [],
                  {#id: id, #idType: idType, #forceRefresh: forceRefresh}),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i8.Future<_i2.UserModel>);
  @override
  _i8.Future<_i3.CategoryModel> getCategory(
          {String? id, String? idType, bool? forceRefresh}) =>
      (super.noSuchMethod(
              Invocation.method(#getCategory, [],
                  {#id: id, #idType: idType, #forceRefresh: forceRefresh}),
              returnValue:
                  Future<_i3.CategoryModel>.value(_FakeCategoryModel_1()))
          as _i8.Future<_i3.CategoryModel>);
  @override
  _i8.Future<_i4.TagModel> getTag(
          {String? id, String? idType, bool? forceRefresh}) =>
      (super.noSuchMethod(
              Invocation.method(#getTag, [],
                  {#id: id, #idType: idType, #forceRefresh: forceRefresh}),
              returnValue: Future<_i4.TagModel>.value(_FakeTagModel_2()))
          as _i8.Future<_i4.TagModel>);
  @override
  _i8.Future<_i5.PostListModel> getPosts(
          {String? search,
          List<String>? notIn,
          List<String>? authorIn,
          List<String>? categoryIn,
          List<String>? categoryNotIn,
          List<String>? tagIn,
          List<String>? tagNotIn,
          int? first,
          String? after,
          int? last,
          String? before,
          bool? forceRefresh}) =>
      (super.noSuchMethod(
              Invocation.method(#getPosts, [], {
                #search: search,
                #notIn: notIn,
                #authorIn: authorIn,
                #categoryIn: categoryIn,
                #categoryNotIn: categoryNotIn,
                #tagIn: tagIn,
                #tagNotIn: tagNotIn,
                #first: first,
                #after: after,
                #last: last,
                #before: before,
                #forceRefresh: forceRefresh
              }),
              returnValue:
                  Future<_i5.PostListModel>.value(_FakePostListModel_3()))
          as _i8.Future<_i5.PostListModel>);
  @override
  _i8.Future<_i6.PostModel> getPost(
          {String? id, String? idType, bool? forceRefresh}) =>
      (super.noSuchMethod(
              Invocation.method(#getPost, [],
                  {#id: id, #idType: idType, #forceRefresh: forceRefresh}),
              returnValue: Future<_i6.PostModel>.value(_FakePostModel_4()))
          as _i8.Future<_i6.PostModel>);
}
