// Mocks generated by Mockito 5.3.2 from annotations
// in kweeksnews_app/test/features/saved_posts/data/repositories/saved_posts_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kweeksnews_app/core/data/datasources/saved_posts_local_data_source.dart'
    as _i3;
import 'package:kweeksnews_app/core/data/models/post_model.dart' as _i5;
import 'package:kweeksnews_app/core/domain/entities/posts.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosts_0 extends _i1.SmartFake implements _i2.Posts {
  _FakePosts_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SavedPostsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedPostsLocalDataSource extends _i1.Mock
    implements _i3.SavedPostsLocalDataSource {
  MockSavedPostsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> createSavedPost({required _i5.PostModel? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSavedPost,
          [],
          {#post: post},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<_i2.Posts> readSavedPosts({
    required int? postsCount,
    required int? pageKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readSavedPosts,
          [],
          {
            #postsCount: postsCount,
            #pageKey: pageKey,
          },
        ),
        returnValue: _i4.Future<_i2.Posts>.value(_FakePosts_0(
          this,
          Invocation.method(
            #readSavedPosts,
            [],
            {
              #postsCount: postsCount,
              #pageKey: pageKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.Posts>);
  @override
  _i4.Future<int> updateSavedPost({required _i5.PostModel? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSavedPost,
          [],
          {#post: post},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<int> deleteSavedPost({required int? postId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedPost,
          [],
          {#postId: postId},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<bool> checkPostSaveStatus({required int? postId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPostSaveStatus,
          [],
          {#postId: postId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
