// Mocks generated by Mockito 5.3.2 from annotations
// in kweeksnews_app/test/features/settings/data/repositories/settings_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui';

import 'package:flutter/material.dart' as _i5;
import 'package:kweeksnews_app/features/settings/data/datasources/locale_local_data_source.dart'
    as _i2;
import 'package:kweeksnews_app/features/settings/data/datasources/theme_local_data_source.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocaleLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleLocalDataSource extends _i1.Mock
    implements _i2.LocaleLocalDataSource {
  MockLocaleLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Locale> getLocale() => (super.noSuchMethod(
        Invocation.method(
          #getLocale,
          [],
        ),
        returnValue: _i3.Future<Locale>.value(Locale('id')),
      ) as _i3.Future<Locale>);
  @override
  _i3.Future<Locale> setLocale(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [languageCode],
        ),
        returnValue: _i3.Future<Locale>.value(Locale('id')),
      ) as _i3.Future<Locale>);
}

/// A class which mocks [ThemeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeLocalDataSource extends _i1.Mock
    implements _i4.ThemeLocalDataSource {
  MockThemeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.ThemeMode> getTheme() => (super.noSuchMethod(
        Invocation.method(
          #getTheme,
          [],
        ),
        returnValue: _i3.Future<_i5.ThemeMode>.value(_i5.ThemeMode.system),
      ) as _i3.Future<_i5.ThemeMode>);
  @override
  _i3.Future<_i5.ThemeMode> setTheme(_i5.ThemeMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValue: _i3.Future<_i5.ThemeMode>.value(_i5.ThemeMode.system),
      ) as _i3.Future<_i5.ThemeMode>);
}
