// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYklFhnDYlRmNJtSn90JIl_K0IJin0H0',
    appId: '1:1026588980320:android:956122162c7fd1d588ff05',
    messagingSenderId: '1026588980320',
    projectId: 'kweeksnews-26038',
    storageBucket: 'kweeksnews-26038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGURM61qeBulaDP9reX_iliEGSLn2ZA2w',
    appId: '1:1026588980320:ios:6eb33ff562b5b8f488ff05',
    messagingSenderId: '1026588980320',
    projectId: 'kweeksnews-26038',
    storageBucket: 'kweeksnews-26038.appspot.com',
    androidClientId:
        '1026588980320-9l9ccpsso0lq5q6g1ae6pgd0osr1ffgb.apps.googleusercontent.com',
    iosClientId:
        '1026588980320-huv68g6bq4em691fp4b1s5a24t8jjj0m.apps.googleusercontent.com',
    iosBundleId: 'com.kweeksnews',
  );
}
