import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

mixin THEME {
  static ThemeData light = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xffdd9933),
      primaryVariant: Color(0xffd2691e),
      secondary: Color(0xff8d9440),
      secondaryVariant: Color(0xff616247),
      appBarColor: Color(0xff616247),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highSurfaceLowScaffold,
    blendLevel: 20,
    appBarStyle: FlexAppBarStyle.background,
    appBarOpacity: 0.95,
    appBarElevation: 0,
    transparentStatusBar: true,
    tabBarStyle: FlexTabBarStyle.forBackground,
    tooltipsMatchBackground: true,
    swapColors: false,
    lightIsWhite: true,
    useSubThemes: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    fontFamily: 'Quicksand',
    subThemesData: const FlexSubThemesData(
      useTextTheme: true,
      fabUseShape: true,
      interactionEffects: true,
      bottomNavigationBarElevation: 0,
      bottomNavigationBarOpacity: 0.95,
      navigationBarOpacity: 0.95,
      navigationBarMutedUnselectedText: true,
      navigationBarMutedUnselectedIcon: true,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorUnfocusedHasBorder: false,
      blendOnColors: true,
      blendTextTheme: false,
      popupMenuOpacity: 0.95,
    ),
  );

  static ThemeData dark = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xffdd9933),
      primaryVariant: Color(0xffd2691e),
      secondary: Color(0xff8d9440),
      secondaryVariant: Color(0xff616247),
      appBarColor: Color(0xff616247),
      error: Color(0xffb00020),
    ).defaultError.toDark(15),
    surfaceMode: FlexSurfaceMode.highSurfaceLowScaffold,
    blendLevel: 20,
    appBarStyle: FlexAppBarStyle.background,
    appBarOpacity: 0.95,
    appBarElevation: 0,
    transparentStatusBar: true,
    tabBarStyle: FlexTabBarStyle.forBackground,
    tooltipsMatchBackground: true,
    swapColors: false,
    darkIsTrueBlack: true,
    useSubThemes: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    fontFamily: 'Quicksand',
    subThemesData: const FlexSubThemesData(
      useTextTheme: true,
      fabUseShape: true,
      interactionEffects: true,
      bottomNavigationBarElevation: 0,
      bottomNavigationBarOpacity: 0.95,
      navigationBarOpacity: 0.95,
      navigationBarMutedUnselectedText: true,
      navigationBarMutedUnselectedIcon: true,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorUnfocusedHasBorder: false,
      blendOnColors: true,
      blendTextTheme: false,
      popupMenuOpacity: 0.95,
    ),
  );
}
